packages:
  - "apps/*"
  - "packages/*"

catalog:
  '@types/node': ^25.3.3
  '@types/react': ^19.2.0
  '@types/react-dom': ^19.2.0
  '@vitejs/plugin-react': ^5.0.4
  react: 19.1.0
  react-dom: 19.1.0
  typescript: ^5.9.3
  vite: ^7.3.2

minimumReleaseAge: 1440
autoInstallPeers: false
onlyBuiltDependencies:
  - esbuild
allowBuilds:
  esbuild: true
